/* JAY AMBE SOFA FURNITURE CATALOG DATA - LOCAL IMG ASSETS ONLY */
const FURNITURE_PRODUCTS = [
  {
    id: "haven-boucle-sofa",
    slug: "haven-boucle-sofa",
    category: "sofas",
    categoryName: "Sofas",
    title: "Haven Cream Bouclé 3-Seater Sofa",
    price: "$1,850",
    rawPrice: 1850,
    image: "./img/sofa-1.jpg",
    description: "Plush, rounded silhouette upholstered in tactile textured bouclé. Deep seating engineered with high-resilience memory foam for everyday living.",
    dimensions: "W: 230cm × D: 98cm × H: 75cm",
    material: "Textured Bouclé Fabric & Kiln-Dried Hardwood",
    leadTime: "3–5 Business Days",
    rating: 4.9,
    reviewsCount: 38
  },
  {
    id: "roma-leather-sofa",
    slug: "roma-leather-sofa",
    category: "sofas",
    categoryName: "Sofas",
    title: "Roma Italian Cognac Leather Sofa",
    price: "$2,400",
    rawPrice: 2400,
    image: "./img/sofa-2.jpg",
    description: "Full-grain Italian cognac leather sofa with delicate tufted detailing and tapered solid walnut legs. Develops a warm vintage patina over time.",
    dimensions: "W: 220cm × D: 92cm × H: 82cm",
    material: "Top-grain Aniline Leather & Solid Walnut",
    leadTime: "1–2 Weeks",
    rating: 5.0,
    reviewsCount: 24
  },
  {
    id: "lille-cloud-sofa",
    slug: "lille-cloud-sofa",
    category: "sofas",
    categoryName: "Sofas",
    title: "Lille Minimalist Modern Sofa",
    price: "$1,650",
    rawPrice: 1650,
    image: "./img/sofa.jpg",
    description: "Clean architectural 3-seat sofa with slim metal pin legs, deep feather-blend cushions, and soft linen upholstery.",
    dimensions: "W: 215cm × D: 90cm × H: 78cm",
    material: "Natural Linen Blend & Matte Steel Legs",
    leadTime: "In Stock",
    rating: 4.8,
    reviewsCount: 29
  },
  {
    id: "fluted-walnut-sideboard",
    slug: "fluted-walnut-sideboard",
    category: "sideboards",
    categoryName: "Sideboards",
    title: "Aura Fluted Walnut Credenza",
    price: "$1,250",
    rawPrice: 1250,
    image: "./img/sideboard-1.jpg",
    description: "Handcrafted dark walnut sideboard featuring tambour fluted sliding panels, integrated brass handles, and soft-close German hardware.",
    dimensions: "W: 180cm × D: 45cm × H: 76cm",
    material: "Solid American Walnut & Brushed Brass",
    leadTime: "1 Week",
    rating: 4.9,
    reviewsCount: 42
  },
  {
    id: "nordic-oak-sideboard",
    slug: "nordic-oak-sideboard",
    category: "sideboards",
    categoryName: "Sideboards",
    title: "Nordic Natural Oak Lowboard",
    price: "$1,120",
    rawPrice: 1120,
    image: "./img/sideboard.jpg",
    description: "Low-slung minimalist media unit crafted in solid white oak with seamless push-to-open cabinets and cord organization channels.",
    dimensions: "W: 170cm × D: 42cm × H: 58cm",
    material: "Solid White Oak with Matte Clear Finish",
    leadTime: "In Stock",
    rating: 4.8,
    reviewsCount: 31
  },
  {
    id: "heritage-cabinet",
    slug: "heritage-cabinet",
    category: "sideboards",
    categoryName: "Sideboards",
    title: "Artisanal Studio Storage Console",
    price: "$1,380",
    rawPrice: 1380,
    image: "./img/about.jpg",
    description: "Warm sunlit timber storage buffet featuring vertical fluting and subtle rounded corners designed for dining and living interiors.",
    dimensions: "W: 160cm × D: 46cm × H: 80cm",
    material: "Kiln-Dried European Ash & Brass Hardware",
    leadTime: "1–2 Weeks",
    rating: 5.0,
    reviewsCount: 19
  },
  {
    id: "kumo-boucle-chair",
    slug: "kumo-boucle-chair",
    category: "chairs",
    categoryName: "Organic Form Chair",
    title: "Kumo Organic Form Lounge Chair",
    price: "$780",
    rawPrice: 780,
    image: "./img/chair-1.jpg",
    description: "Sculptural cocoon-like accent lounge chair wrapped in soft oatmeal bouclé with an ultra-smooth 360-degree concealed swivel base.",
    dimensions: "W: 95cm × D: 90cm × H: 80cm",
    material: "Textured Oatmeal Bouclé & Heavy Base",
    leadTime: "In Stock",
    rating: 5.0,
    reviewsCount: 56
  },
  {
    id: "sculptural-armchair",
    slug: "sculptural-armchair",
    category: "chairs",
    categoryName: "Organic Form Chair",
    title: "Vessel Minimalist Accent Armchair",
    price: "$820",
    rawPrice: 820,
    image: "./img/chair.jpg",
    description: "Curved enveloping lounge armchair designed with ergonomic lumbar support and woven tactile linen blend upholstery.",
    dimensions: "W: 86cm × D: 82cm × H: 76cm",
    material: "Natural Flax Linen & Steel Subframe",
    leadTime: "3–5 Days",
    rating: 4.9,
    reviewsCount: 34
  },
  {
    id: "reading-nook-chair",
    slug: "reading-nook-chair",
    category: "chairs",
    categoryName: "Organic Form Chair",
    title: "Studio Corner Reading Chair",
    price: "$690",
    rawPrice: 690,
    image: "./img/reel-4.jpg",
    description: "Low-profile accent chair paired with warm ambient proportions for reading corners, bedrooms, and quiet lounges.",
    dimensions: "W: 80cm × D: 80cm × H: 74cm",
    material: "Textured Wool Fabric & Oak Base",
    leadTime: "In Stock",
    rating: 4.7,
    reviewsCount: 22
  },
  {
    id: "sora-oak-dining-table",
    slug: "sora-oak-dining-table",
    category: "tables",
    categoryName: "Dining Tables",
    title: "Sora Round Solid Oak Dining Table",
    price: "$1,350",
    rawPrice: 1350,
    image: "./img/table-1.jpg",
    description: "Circular dining table carved from solid white oak with gently beveled edges and splayed solid legs. Comfortably seats 4–6 persons.",
    dimensions: "Diameter: 130cm × H: 75cm",
    material: "Solid European White Oak",
    leadTime: "1–2 Weeks",
    rating: 4.9,
    reviewsCount: 45
  },
  {
    id: "nordic-dining-set",
    slug: "nordic-dining-set",
    category: "tables",
    categoryName: "Dining Tables",
    title: "Kyoto Round Oak Table Set",
    price: "$1,480",
    rawPrice: 1480,
    image: "./img/table.jpg",
    description: "Minimalist round solid wood dining table finished with organic clear oils to emphasize the natural timber grain pattern.",
    dimensions: "Diameter: 120cm × H: 75cm",
    material: "Solid White Oak with Matte Wax Finish",
    leadTime: "In Stock",
    rating: 5.0,
    reviewsCount: 28
  },
  {
    id: "dining-nook-table",
    slug: "dining-nook-table",
    category: "tables",
    categoryName: "Dining Tables",
    title: "Cove Woven Accent Dining Table",
    price: "$1,290",
    rawPrice: 1290,
    image: "./img/reel-3.jpg",
    description: "Thoughtfully sized dining table ideal for breakfast nooks, apartments, and open-plan kitchen spaces.",
    dimensions: "W: 140cm × D: 80cm × H: 75cm",
    material: "Solid Ash Wood with Smooth Planed Top",
    leadTime: "1 Week",
    rating: 4.8,
    reviewsCount: 17
  },
  {
    id: "solstice-rattan-swing",
    slug: "solstice-rattan-swing",
    category: "swings",
    categoryName: "Swing Seating",
    title: "Solstice Rattan Hanging Swing Pod",
    price: "$850",
    rawPrice: 850,
    image: "./img/swing-1.jpg",
    description: "Hand-woven natural rattan swing chair featuring reinforced core strapping, heavy-duty stainless steel carabiner, and plush outdoor cushion.",
    dimensions: "W: 98cm × D: 85cm × H: 125cm",
    material: "All-Weather Woven Rattan & Sunbrella Cushion",
    leadTime: "In Stock",
    rating: 4.9,
    reviewsCount: 52
  },
  {
    id: "breeze-hanging-chair",
    slug: "breeze-hanging-chair",
    category: "swings",
    categoryName: "Swing Seating",
    title: "Breeze Natural Cane Swing Cradle",
    price: "$790",
    rawPrice: 790,
    image: "./img/swing.jpg",
    description: "Organic handwoven cane hanging pod with thick cream base cushion, designed for indoor balconies, sunrooms, and verandas.",
    dimensions: "W: 92cm × D: 80cm × H: 120cm",
    material: "Natural Cane, Jute Rope & Weatherproof Foam",
    leadTime: "In Stock",
    rating: 4.9,
    reviewsCount: 39
  },
  {
    id: "canopy-lounge-pod",
    slug: "canopy-lounge-pod",
    category: "swings",
    categoryName: "Swing Seating",
    title: "Canopy Relaxing Swing Hammock",
    price: "$880",
    rawPrice: 880,
    image: "./img/reel-1.jpg",
    description: "Suspended relaxing daybed swing crafted with solid hardwood spreader bars and heavy-duty natural canvas straps.",
    dimensions: "W: 105cm × D: 90cm × H: 130cm",
    material: "Solid Teak & Double-Stitched Cotton Duck",
    leadTime: "3–5 Days",
    rating: 4.8,
    reviewsCount: 21
  }
];
