/* JAY AMBE SOFA FURNITURE CATALOG DATA - INDIAN MARKET PRICING (INR ₹) & LOCALISATION */
const FURNITURE_PRODUCTS = [
  {
    id: "haven-boucle-sofa",
    slug: "haven-boucle-sofa",
    category: "sofas",
    categoryName: "Sofas",
    title: "Haven Cream Bouclé 3-Seater Sofa",
    price: "₹48,500",
    rawPrice: 48500,
    image: "./img/sofa-1.webp",
    description: "Plush, rounded silhouette upholstered in premium tactile textured bouclé. Deep seating engineered with high-resilience memory foam and solid sagwan/hardwood frame for everyday living.",
    dimensions: "W: 230cm × D: 98cm × H: 75cm (7.5 ft × 3.2 ft)",
    material: "Textured Bouclé Fabric & Kiln-Dried Solid Hardwood",
    leadTime: "In Stock / 3–5 Days",
    rating: 4.9,
    reviewsCount: 38
  },
  {
    id: "roma-leather-sofa",
    slug: "roma-leather-sofa",
    category: "sofas",
    categoryName: "Sofas",
    title: "Roma Italian Cognac Leatherette Sofa",
    price: "₹64,000",
    rawPrice: 64000,
    image: "./img/sofa-2.webp",
    description: "Full-grain rich cognac leatherette sofa with delicate tufted detailing and tapered solid wooden legs. Breathable, durable upholstery tailored for Indian climate conditions.",
    dimensions: "W: 220cm × D: 92cm × H: 82cm (7.2 ft × 3.0 ft)",
    material: "Premium Breathable Leatherette & Solid Wood Frame",
    leadTime: "1–2 Weeks",
    rating: 5.0,
    reviewsCount: 24
  },
  {
    id: "lille-cloud-sofa",
    slug: "lille-cloud-sofa",
    category: "sofas",
    categoryName: "Sofas",
    title: "Lille Minimalist Modern Sofa",
    price: "₹42,000",
    rawPrice: 42000,
    image: "./img/sofa.webp",
    description: "Clean architectural 3-seater sofa with slim metallic base, deep high-density feather-touch cushions, and soft textured linen upholstery.",
    dimensions: "W: 215cm × D: 90cm × H: 78cm (7.0 ft × 3.0 ft)",
    material: "Natural Linen Blend & Matte Finish Metal Legs",
    leadTime: "In Stock",
    rating: 4.8,
    reviewsCount: 29
  },
  {
    id: "fluted-walnut-sideboard",
    slug: "fluted-walnut-sideboard",
    category: "sideboards",
    categoryName: "Sideboards",
    title: "Aura Fluted Walnut Credenza",
    price: "₹34,500",
    rawPrice: 34500,
    image: "./img/sideboard-1.webp",
    description: "Handcrafted rich walnut finish sideboard featuring tambour fluted sliding panels, integrated brass handles, and soft-close German hardware.",
    dimensions: "W: 180cm × D: 45cm × H: 76cm (5.9 ft × 1.5 ft)",
    material: "Solid Hardwood Core & Natural Walnut Veneer with Brushed Brass",
    leadTime: "1 Week",
    rating: 4.9,
    reviewsCount: 42
  },
  {
    id: "nordic-oak-sideboard",
    slug: "nordic-oak-sideboard",
    category: "sideboards",
    categoryName: "Sideboards",
    title: "Nordic Natural Oak Lowboard",
    price: "₹28,500",
    rawPrice: 28500,
    image: "./img/sideboard.webp",
    description: "Low-slung minimalist TV media console crafted in solid seasoned oak with seamless push-to-open cabinets and integrated cable management.",
    dimensions: "W: 170cm × D: 42cm × H: 58cm (5.5 ft × 1.4 ft)",
    material: "Solid Seasoned Oak with Matte Clear Melamine Finish",
    leadTime: "In Stock",
    rating: 4.8,
    reviewsCount: 31
  },
  {
    id: "heritage-cabinet",
    slug: "heritage-cabinet",
    category: "sideboards",
    categoryName: "Sideboards",
    title: "Artisanal Studio Storage Buffet Console",
    price: "₹36,000",
    rawPrice: 36000,
    image: "./img/about.webp",
    description: "Warm sunlit timber storage cabinet featuring vertical fluting and subtle rounded corners, designed for dining areas and modern flat living rooms.",
    dimensions: "W: 160cm × D: 46cm × H: 80cm (5.2 ft × 1.5 ft)",
    material: "Seasoned Ash Wood & Solid Brass Fittings",
    leadTime: "1–2 Weeks",
    rating: 5.0,
    reviewsCount: 19
  },
  {
    id: "kumo-boucle-chair",
    slug: "kumo-boucle-chair",
    category: "chairs",
    categoryName: "Organic Form Chair",
    title: "Kumo Organic Form Lounge Chair",
    price: "₹18,500",
    rawPrice: 18500,
    image: "./img/chair-1.webp",
    description: "Sculptural cocoon-like accent lounge chair wrapped in soft oatmeal bouclé with an ultra-smooth 360-degree concealed heavy-duty swivel base.",
    dimensions: "W: 95cm × D: 90cm × H: 80cm (3.1 ft × 2.9 ft)",
    material: "Textured Oatmeal Bouclé & Heavy Steel Swivel Base",
    leadTime: "In Stock",
    rating: 5.0,
    reviewsCount: 56
  },
  {
    id: "sculptural-armchair",
    slug: "sculptural-armchair",
    category: "chairs",
    categoryName: "Organic Form Chair",
    title: "Vessel Minimalist Accent Armchair",
    price: "₹19,800",
    rawPrice: 19800,
    image: "./img/chair.webp",
    description: "Curved enveloping lounge armchair designed with ergonomic lumbar support and woven tactile linen-blend upholstery for maximum sitting comfort.",
    dimensions: "W: 86cm × D: 82cm × H: 76cm (2.8 ft × 2.7 ft)",
    material: "Natural Flax Linen & Solid Hardwood Subframe",
    leadTime: "3–5 Days",
    rating: 4.9,
    reviewsCount: 34
  },
  {
    id: "reading-nook-chair",
    slug: "reading-nook-chair",
    category: "chairs",
    categoryName: "Organic Form Chair",
    title: "Studio Corner Reading Chair",
    price: "₹16,500",
    rawPrice: 16500,
    image: "./img/reel-4.webp",
    description: "Low-profile accent chair paired with warm ambient proportions for bedroom corners, master suites, and quiet reading lounges.",
    dimensions: "W: 80cm × D: 80cm × H: 74cm (2.6 ft × 2.6 ft)",
    material: "Textured Upholstery Fabric & Solid Wood Legs",
    leadTime: "In Stock",
    rating: 4.7,
    reviewsCount: 22
  },
  {
    id: "sora-oak-dining-table",
    slug: "sora-oak-dining-table",
    category: "tables",
    categoryName: "Dining Tables",
    title: "Sora Round Solid Wood Dining Table",
    price: "₹34,000",
    rawPrice: 34000,
    image: "./img/table-1.webp",
    description: "Circular dining table carved from solid seasoned wood with gently bevelled edges and splayed solid legs. Comfortably seats 4 to 6 people.",
    dimensions: "Diameter: 130cm × H: 75cm (4.25 ft round)",
    material: "Solid Seasoned Wood & Moisture-Resistant PU Polish",
    leadTime: "1–2 Weeks",
    rating: 4.9,
    reviewsCount: 45
  },
  {
    id: "nordic-dining-set",
    slug: "nordic-dining-set",
    category: "tables",
    categoryName: "Dining Tables",
    title: "Kyoto Round Timber Dining Table Set",
    price: "₹38,500",
    rawPrice: 38500,
    image: "./img/table.webp",
    description: "Minimalist round solid wood dining table finished with organic clear sealer to highlight the natural timber grain pattern.",
    dimensions: "Diameter: 120cm × H: 75cm (4.0 ft round)",
    material: "Solid Seasoned Hardwood with Matte Protective Wax Finish",
    leadTime: "In Stock",
    rating: 5.0,
    reviewsCount: 28
  },
  {
    id: "dining-nook-table",
    slug: "dining-nook-table",
    category: "tables",
    categoryName: "Dining Tables",
    title: "Cove Woven Accent Dining Table",
    price: "₹29,500",
    rawPrice: 29500,
    image: "./img/reel-3.webp",
    description: "Thoughtfully sized rectangular dining table ideal for modern flats, villas, and open-plan kitchen-dining spaces in Surat.",
    dimensions: "W: 140cm × D: 80cm × H: 75cm (4.6 ft × 2.6 ft)",
    material: "Solid Hardwood with Smooth Hand-Planed Top",
    leadTime: "1 Week",
    rating: 4.8,
    reviewsCount: 17
  },
  {
    id: "solstice-rattan-swing",
    slug: "solstice-rattan-swing",
    category: "swings",
    categoryName: "Swing Seating",
    title: "Solstice Rattan Hanging Swing (Jhula)",
    price: "₹22,500",
    rawPrice: 22500,
    image: "./img/swing-1.webp",
    description: "Hand-woven natural rattan swing chair featuring reinforced core strapping, heavy-duty stainless steel ceiling hooks, and plush weatherproof seat cushion.",
    dimensions: "W: 98cm × D: 85cm × H: 125cm (3.2 ft × 2.8 ft)",
    material: "All-Weather Woven Rattan & Washable Fabric Cushion",
    leadTime: "In Stock",
    rating: 4.9,
    reviewsCount: 52
  },
  {
    id: "breeze-hanging-chair",
    slug: "breeze-hanging-chair",
    category: "swings",
    categoryName: "Swing Seating",
    title: "Breeze Natural Cane Swing Cradle (Jhula)",
    price: "₹19,000",
    rawPrice: 19000,
    image: "./img/swing.webp",
    description: "Organic handwoven cane hanging pod with thick cream base cushion, specially crafted for balconies, garden verandas, and living rooms.",
    dimensions: "W: 92cm × D: 80cm × H: 120cm (3.0 ft × 2.6 ft)",
    material: "Natural Cane, Jute Rope & High-Density Foam",
    leadTime: "In Stock",
    rating: 4.9,
    reviewsCount: 39
  },
  {
    id: "canopy-lounge-pod",
    slug: "canopy-lounge-pod",
    category: "swings",
    categoryName: "Swing Seating",
    title: "Canopy Relaxing Swing Daybed (Jhula)",
    price: "₹24,500",
    rawPrice: 24500,
    image: "./img/reel-1.webp",
    description: "Suspended relaxing daybed swing crafted with solid hardwood spreader bars and heavy-duty double-stitched natural cotton canvas straps.",
    dimensions: "W: 105cm × D: 90cm × H: 130cm (3.4 ft × 3.0 ft)",
    material: "Solid Teak & Double-Stitched Heavy Cotton Canvas",
    leadTime: "3–5 Days",
    rating: 4.8,
    reviewsCount: 21
  }
];
